/**
 * AUTO-GENERATED by `tests/compile-lexicon.ts` from
 * `src/data/liquidacion-lexicon.yaml`. Do not hand-edit; run
 * `npm run build` (which runs `prebuild`) to regenerate.
 */

import type { Lexicon } from '../liquidacion/types'

export const LEXICON: Lexicon = {
    "version": 1,
    "doctype": "liquidaciones-sueldo",
    "itemTypes": [
        "income",
        "deduction"
    ],
    "items": [
        {
            "id": "sueldo_base",
            "canonical": "Sueldo Base",
            "itemType": "income",
            "aliases": [
                "Sueldo Base",
                "Sueldo",
                "Sueldo Mensual",
                "Sueldo Base Mensual",
                "Remuneración Base",
                "Remuneracion Base"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Imponible"
            }
        },
        {
            "id": "gratificacion",
            "canonical": "Gratificación",
            "itemType": "income",
            "aliases": [
                "Gratificación",
                "Gratificacion",
                "Gratificación Legal",
                "Gratificacion Legal",
                "Gratificación Mensual",
                "Gratificacion Mensual",
                "Grat. Legal",
                "Grat Legal"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Imponible"
            }
        },
        {
            "id": "colacion",
            "canonical": "Colación",
            "itemType": "income",
            "aliases": [
                "Colación",
                "Colacion",
                "Asignación Colación",
                "Asignacion Colacion",
                "Asig. Colación",
                "Asig. Colacion",
                "Asig Colacion",
                "Bono Colación",
                "Bono Colacion"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "No imponible"
            }
        },
        {
            "id": "movilizacion",
            "canonical": "Movilización",
            "itemType": "income",
            "aliases": [
                "Movilización",
                "Movilizacion",
                "Asignación Movilización",
                "Asignacion Movilizacion",
                "Asig. Movilización",
                "Asig. Movilizacion",
                "Asig Movilizacion",
                "Bono Movilización",
                "Bono Movilizacion"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "No imponible"
            }
        },
        {
            "id": "asignacion_familiar",
            "canonical": "Asignación Familiar",
            "itemType": "income",
            "aliases": [
                "Asignación Familiar",
                "Asignacion Familiar",
                "Asig. Familiar",
                "Asig Familiar",
                "Asignación Fam.",
                "Asignacion Fam.",
                "Cargas Familiares"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "No imponible"
            }
        },
        {
            "id": "asignacion_estudios",
            "canonical": "Asignación de Estudios",
            "itemType": "income",
            "aliases": [
                "Asignación de Estudios",
                "Asignacion de Estudios",
                "Asignación Estudios",
                "Asignacion Estudios",
                "Asig. Estudios",
                "Asig Estudios",
                "Bono Estudios",
                "Bono de Estudios"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "No imponible"
            }
        },
        {
            "id": "viatico",
            "canonical": "Viático",
            "itemType": "income",
            "aliases": [
                "Viático",
                "Viatico",
                "Viáticos",
                "Viaticos",
                "Asignación Viático",
                "Asignacion Viatico"
            ],
            "classification": {
                "tipoRenta": "Variable",
                "naturaleza": "No imponible"
            }
        },
        {
            "id": "horas_extras",
            "canonical": "Horas Extras",
            "itemType": "income",
            "aliases": [
                "Horas Extras",
                "Horas Extra",
                "Hrs. Extras",
                "Hrs Extras",
                "H. Extras",
                "HH.EE.",
                "HH EE",
                "Sobretiempo",
                "Sobre Tiempo",
                "Sobresueldo"
            ],
            "classification": {
                "tipoRenta": "Variable",
                "naturaleza": "Imponible"
            }
        },
        {
            "id": "comisiones",
            "canonical": "Comisiones",
            "itemType": "income",
            "aliases": [
                "Comisiones",
                "Comisión",
                "Comision",
                "Comisión de Ventas",
                "Comision de Ventas",
                "Comisiones de Venta",
                "Comisiones Ventas"
            ],
            "classification": {
                "tipoRenta": "Variable",
                "naturaleza": "Imponible"
            }
        },
        {
            "id": "aguinaldo",
            "canonical": "Aguinaldo",
            "itemType": "income",
            "aliases": [
                "Aguinaldo",
                "Aguinaldo Fiestas Patrias",
                "Aguinaldo Navidad",
                "Aguinaldo de Fiestas Patrias",
                "Aguinaldo de Navidad",
                "Bono Fiestas Patrias",
                "Bono Navidad",
                "Bono de Navidad",
                "Bono de Fiestas Patrias"
            ],
            "classification": {
                "tipoRenta": "Variable",
                "naturaleza": "Imponible"
            }
        },
        {
            "id": "vacaciones",
            "canonical": "Vacaciones",
            "itemType": "income",
            "aliases": [
                "Vacaciones",
                "Feriado Legal",
                "Feriado Anual",
                "Pago Vacaciones",
                "Remuneración Vacaciones",
                "Remuneracion Vacaciones"
            ],
            "classification": {
                "tipoRenta": "Variable",
                "naturaleza": "Imponible"
            }
        },
        {
            "id": "afp_cotizacion_obligatoria",
            "canonical": "Cotiz. Previsional Obligatoria",
            "itemType": "deduction",
            "aliases": [
                "AFP",
                "Cotización AFP",
                "Cotizacion AFP",
                "Cotiz. AFP",
                "Cotiz AFP",
                "Cotiz. Previsional Obligatoria",
                "Cotizacion Previsional Obligatoria",
                "Cotización Previsional Obligatoria",
                "Cotiz. Previ. Obligatoria",
                "Cotiz Previ Obligatoria",
                "Cotización Previsional",
                "Cotizacion Previsional",
                "Capitalización Individual",
                "Capitalizacion Individual",
                "Capitalización Individual 10%",
                "Capitalizacion Individual 10%",
                "AFP Obligatoria",
                "Previsión AFP",
                "Prevision AFP"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Legal",
                "legalType": "afp"
            }
        },
        {
            "id": "comision_afp",
            "canonical": "Comisión AFP",
            "itemType": "deduction",
            "aliases": [
                "Comisión AFP",
                "Comision AFP",
                "Comisión A.F.P.",
                "Comision A.F.P.",
                "Comisión Administradora",
                "Comision Administradora",
                "Comisión Adm. AFP",
                "Comision Adm AFP"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Legal",
                "legalType": "afp"
            }
        },
        {
            "id": "salud_obligatoria",
            "canonical": "Cotiz. Salud Obligatoria",
            "itemType": "deduction",
            "aliases": [
                "Salud 7%",
                "Salud 7",
                "Salud Obligatoria",
                "Salud",
                "Cotización Salud",
                "Cotizacion Salud",
                "Cotiz. Salud",
                "Cotiz Salud",
                "Cotiz. Salud Obligatoria",
                "Cotizacion Salud Obligatoria",
                "Cotización Salud Obligatoria",
                "Cotiz. Salud Obligatoria 7%",
                "Cotizacion Salud Obligatoria 7%",
                "Cotización Salud Obligatoria 7%",
                "Fonasa",
                "Isapre",
                "Cotización Isapre",
                "Cotizacion Isapre"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Legal",
                "legalType": "salud"
            }
        },
        {
            "id": "adicional_salud",
            "canonical": "Adicional Salud",
            "itemType": "deduction",
            "aliases": [
                "Adicional Salud",
                "Adicional de Salud",
                "Cotización Adicional Salud",
                "Cotizacion Adicional Salud",
                "Cotiz. Adicional Salud",
                "Cotiz Adicional Salud",
                "Salud Adicional",
                "Salud Voluntaria",
                "Cotización Voluntaria Salud",
                "Cotizacion Voluntaria Salud",
                "Pactado Isapre",
                "Adicional Isapre"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Otro"
            }
        },
        {
            "id": "seguro_cesantia",
            "canonical": "Seguro de Cesantía",
            "itemType": "deduction",
            "aliases": [
                "Seguro de Cesantía",
                "Seguro de Cesantia",
                "Seguro Cesantía",
                "Seguro Cesantia",
                "Seguro de Cesantía 0,6%",
                "Seguro de Cesantia 0,6%",
                "Seguro Cesantía 0,6%",
                "Seguro Cesantia 0,6%",
                "Cesantía",
                "Cesantia",
                "Cesantía 0,6%",
                "Cesantia 0,6%",
                "AFC",
                "AFC 0,6%",
                "Cotización AFC",
                "Cotizacion AFC",
                "Cotiz. AFC",
                "Cotiz AFC",
                "Aporte Trabajador AFC"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Legal",
                "legalType": "cesantia"
            }
        },
        {
            "id": "impuesto_unico",
            "canonical": "Impuesto Único",
            "itemType": "deduction",
            "aliases": [
                "Impuesto Único",
                "Impuesto Unico",
                "Impuesto Único de Segunda Categoría",
                "Impuesto Unico de Segunda Categoria",
                "Impuesto 2da Categoría",
                "Impuesto 2da Categoria",
                "Impuesto Segunda Categoría",
                "Impuesto Segunda Categoria",
                "Imp. Único",
                "Imp. Unico",
                "IUSC"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Legal",
                "legalType": "impuesto"
            }
        },
        {
            "id": "anticipo",
            "canonical": "Anticipo",
            "itemType": "deduction",
            "aliases": [
                "Anticipo",
                "Anticipos",
                "Anticipo de Sueldo",
                "Anticipo Sueldo",
                "Anticipo Quincenal",
                "Anticipo Remuneración",
                "Anticipo Remuneracion"
            ],
            "classification": {
                "tipoRenta": "Variable",
                "naturaleza": "Otro"
            }
        },
        {
            "id": "prestamo_empresa",
            "canonical": "Préstamo Empresa",
            "itemType": "deduction",
            "aliases": [
                "Préstamo Empresa",
                "Prestamo Empresa",
                "Préstamo de Empresa",
                "Prestamo de Empresa",
                "Préstamo",
                "Prestamo",
                "Préstamo Empleador",
                "Prestamo Empleador",
                "Cuota Préstamo",
                "Cuota Prestamo",
                "Descuento Préstamo",
                "Descuento Prestamo"
            ],
            "classification": {
                "tipoRenta": "Variable",
                "naturaleza": "Otro"
            }
        },
        {
            "id": "caja_compensacion",
            "canonical": "Caja de Compensación",
            "itemType": "deduction",
            "aliases": [
                "Caja de Compensación",
                "Caja de Compensacion",
                "Caja Compensación",
                "Caja Compensacion",
                "C.C.A.F.",
                "CCAF",
                "Cuota CCAF",
                "Aporte CCAF",
                "Descuento CCAF"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Otro"
            }
        },
        {
            "id": "cuota_sindical",
            "canonical": "Cuota Sindical",
            "itemType": "deduction",
            "aliases": [
                "Cuota Sindical",
                "Cuota Sindicato",
                "Sindicato",
                "Aporte Sindical",
                "Descuento Sindical",
                "Descuento Sindicato"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Otro"
            }
        },
        {
            "id": "seguro_complementario",
            "canonical": "Seguro Complementario",
            "itemType": "deduction",
            "aliases": [
                "Seguro Complementario",
                "Seguro Complementario de Salud",
                "Seguro Complementario Salud",
                "Seguro de Salud Complementario",
                "Seguro Colectivo",
                "Seguro Colectivo de Salud",
                "Seguro Colectivo Salud",
                "Seguro Vida",
                "Seguro de Vida"
            ],
            "classification": {
                "tipoRenta": "Fija",
                "naturaleza": "Otro"
            }
        }
    ]
} as const as Lexicon
